import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:wigtoday_app/app/user/models/user_cache.dart';

class UserProFileModle with ChangeNotifier {
  
  int id; // 132375,
  int siteId; // 10005,
  String account; // "312790696@qq.com",
  String authEmail; // "312790696@qq.com",
  String authPhone; // "",
  String password; // "ac81b21ce62e1edac4b858ebd89daf76da780533",
  String avatar; // "/avatar/af4e0c06191ea4fc6653a85ca4e4b5a5.png",
  String countryCode; // "",
  int status; // 0,
  int createTime; // 1634085077,
  int uid; // 132375,
  int userId; // 132375,
  int registerType; // 0,
  int isEmail; // 1,
  int isLiar; // 0,
  String payPassword; // "97a4c2b3c5988f61adc9dd0f2f78cbc0",
  int isAd; // 0,
  int isPromoter; // 1,
  int isCredentials; // 0,
  int isSubion; // 1,
  String createCountry; // "China",
  String createIsocode; // "CN",
  String createOs; // "Windows 10",
  String createBrowser; // "Chrome(94.0.4606.61)",
  String createDomain; // "www.wigtoday.com",
  String score; // "50.00",
  int lastTime; // 1645768168,
  String consume; // "0.00",
  int exp; // 0,
  int level; // 0,
  String changeScore; // "0.00",
  String appUuid; // "",
  String siteName; // "WIGTODAY",
  String firstName; // "zhu",
  String lastName; // "xueyi",
  int updateTime; // 1634085077,
  int gender; // 1,
  String phone; // "15215628962",
  String yahoo; // "",
  String icq; // "",
  String qq; // "",
  String skype; // "",
  String otherInstant; // "",
  String country; // "奥地利",
  String address; // "TongChina Sdfasfadafdsaf",
  String email; // "",
  String msn; // "",
  String birthday; // "03-20",
  String remark; // ""
  String token;

  String? recommendCode; // null,
  int? type; // null,
  String? securityAnswer; // null,
  int? securityQuestionId; // null,

  bool get hasVerifyEmail => authEmail.isNotEmpty;

  bool get isMan => gender == 1 ? true : false;

  UserProFileModle({
    required this.id, // 132375,
    required this.siteId, // 10005,
    required this.userId, // 132375,
    required this.uid, // 132375,
    required this.registerType, // 0,
    required this.isEmail, // 1,
    required this.isLiar, // 0,
    required this.isAd, // 0,
    required this.isPromoter, // 1,
    required this.isCredentials, // 0,
    required this.isSubion, // 1,
    required this.lastTime, // 1645768168,
    required this.exp, // 0,
    required this.level, // 0,
    required this.status, // 0,
    required this.createTime, // 1634085077,
    required this.token,
    this.recommendCode, // null,
    this.type, // null,
    this.securityAnswer, // null,
    this.securityQuestionId, // null,

    this.account = "", // "312790696@qq.com",
    this.authEmail = "", // "312790696@qq.com",
    this.authPhone = "", // "",
    this.password = "", // "ac81b21ce62e1edac4b858ebd89daf76da780533",
    this.avatar = "", // "/avatar/af4e0c06191ea4fc6653a85ca4e4b5a5.png",
    this.countryCode = "", // "",
    this.payPassword = "", // "97a4c2b3c5988f61adc9dd0f2f78cbc0",
    this.createCountry = "", // "China",
    this.createIsocode = "", // "CN",
    this.createOs = "", // "Windows 10",
    this.createBrowser = "", // "Chrome(94.0.4606.61)",
    this.createDomain = "", // "www.wigtoday.com",
    this.score = "", // "50.00",
    this.consume = "", // "0.00",
    this.changeScore = "", // "0.00",
    this.appUuid = "", // "",
    this.siteName = "", // "WIGTODAY",
    this.firstName = "", // "zhu",
    this.lastName = "", // "xueyi",
    this.updateTime = -1, // 1634085077,
    this.gender = -1, // 1,
    this.phone = "", // "15215628962",
    this.yahoo = "", // "",
    this.icq = "", // "",
    this.qq = "", // "",
    this.skype = "", // "",
    this.otherInstant = "", // "",
    this.country = "", // "奥地利",
    this.address = "", // "TongChina Sdfasfadafdsaf",
    this.email = "", // "",
    this.msn = "", // "",
    this.birthday = "", // "03-20",
    this.remark = "", // ""
  });

  static UserProFileModle getGuestModel() {
    return UserProFileModle(
        id: -1,
        siteId: -1,
        userId: -1,
        uid: -1,
        registerType: -1,
        isEmail: -1,
        isLiar: -1,
        isAd: -1,
        isPromoter: -1,
        isCredentials: -01,
        isSubion: -1,
        lastTime: -1,
        exp: -1,
        level: -1,
        status: -1,
        createTime: -1,
        token: '');
  }

  static UserProFileModle fromResponse(Map<String, dynamic> data) {
    Map d = data['data'];
    return UserProFileModle(
      id: d['id'],
      siteId: d['site_id'],
      userId: d['user_id'],
      registerType: d['register_type'],
      isEmail: d['is_email'],
      isLiar: d['is_liar'],
      isAd: d['is_ad'],
      isPromoter: d['is_promoter'],
      isCredentials: d['is_credentials'],
      isSubion: d['is_subion'],
      lastTime: d['last_time'],
      exp: d['exp'],
      level: d['level'],
      status: d['status'],
      createTime: d['create_time'],
      uid: d['uid'],
      token: d['token'],

      recommendCode: d['recommend_code'], // null,
      type: d['type'], // null,
      securityAnswer: d['security_answer'], // null,
      securityQuestionId: d['security_question_id'], // null,

      account: d["account"], // "312790696@qq.com",
      authEmail: d["auth_email"], // "312790696@qq.com",
      authPhone: d["auth_phone"], // "",
      password: d["password"], // "ac81b21ce62e1edac4b858ebd89daf76da780533",
      avatar: d["avatar"], // "/avatar/af4e0c06191ea4fc6653a85ca4e4b5a5.png",
      countryCode: d["country_code"], // "",
      payPassword: d["pay_password"], // "97a4c2b3c5988f61adc9dd0f2f78cbc0",
      createCountry: d["create_country"], // "China",
      createIsocode: d["create_isocode"], // "CN",
      createOs: d["create_os"], // "Windows 10",
      createBrowser: d["create_browser"], // "Chrome(94.0.4606.61)",
      createDomain: d["create_domain"], // "www.wigtoday.com",
      score: d["score"], // "50.00",
      consume: d["consume"], // "0.00",
      changeScore: d["change_score"], // "0.00",
      appUuid: d["app_uuid"], // "",
      siteName: d["site_name"], // "WIGTODAY",
      firstName: d["first_name"], // "zhu",
      lastName: d["last_name"], // "xueyi",
      updateTime: d["update_time"], // 1634085077,
      gender: d["gender"], // 1,
      phone: d["phone"], // "15215628962",
      yahoo: d["yahoo"], // "",
      icq: d["icq"], // "",
      qq: d["qq"], // "",
      skype: d["skype"], // "",
      otherInstant: d["other_instant"], // "",
      country: d["country"], // "奥地利",
      address: d["address"], // "TongChina Sdfasfadafdsaf",
      email: d["email"], // "",
      msn: d["msn"], // "",
      birthday: d["birthday"] ?? "", // "03-20",
      remark: d["remark"], // ""
    );
  }

  static UserProFileModle fromJson(String jsonData) {
    var data = jsonDecode(jsonData) as Map<String, dynamic>;
    return UserProFileModle(
        id: data['id'],
        siteId: data['siteId'],
        userId: data['userId'],
        registerType: data['registerType'],
        isEmail: data['isEmail'],
        isLiar: data['isLiar'],
        isAd: data['isAd'],
        isPromoter: data['isPromoter'],
        isCredentials: data['isCredentials'],
        isSubion: data['isSubion'],
        lastTime: data['lastTime'],
        exp: data['exp'],
        level: data['level'],
        status: data['status'],
        createTime: data['createTime'],
        uid: data['uid'],
        token: data['token'],
        recommendCode: data['recommendCode'], // null,
        type: data['type'], // null,
        securityAnswer: data['securityAnswer'], // null,
        securityQuestionId: data['securityQuestionId'], // null,
        account: data['account'], // "312790696@qq.com",
        authEmail: data['authEmail'], // "312790696@qq.com",
        authPhone: data['authPhone'], // "",
        password:
            data['password'], // "ac81b21ce62e1edac4b858ebd89daf76da780533",
        avatar:
            data['avatar'], // "/avatar/af4e0c06191ea4fc6653a85ca4e4b5a5.png",
        countryCode: data['countryCode'], // "",
        payPassword: data['payPassword'], // "97a4c2b3c5988f61adc9dd0f2f78cbc0",
        createCountry: data['createCountry'], // "China",
        createIsocode: data['createIsocode'], // "CN",
        createOs: data['createOs'], // "Windows 10",
        createBrowser: data['createBrowser'], // "Chrome(94.0.4606.61)",
        createDomain: data['createDomain'], // "www.wigtoday.com",
        score: data['score'], // "50.00",
        consume: data['consume'], // "0.00",
        changeScore: data['changeScore'], // "0.00",
        appUuid: data['appUuid'], // "",
        siteName: data['siteName'], // "WIGTODAY",
        firstName: data['firstName'], // "zhu",
        lastName: data['lastName'], // "xueyi",
        updateTime: data['updateTime'], // 1634085077,
        gender: data['gender'], // 1,
        phone: data['phone'], // "15215628962",
        yahoo: data['yahoo'], // "",
        icq: data['icq'], // "",
        qq: data['qq'], // "",
        skype: data['skype'], // "",
        otherInstant: data['otherInstant'], // "",
        country: data['country'], // "奥地利",
        address: data['address'], // "TongChina Sdfasfadafdsaf",
        email: data['email'], // "",
        msn: data['msn'], // "",
        birthday: data['birthday'], // "03-20",
        remark: data['remark']);
  }

  UserCacheModel getUserCacheModel(
      {required bool isActive, required String pwd, int? createTime}) {
    return UserCacheModel(
        userId: userId,
        account: account,
        passwd: pwd,
        isActive: isActive,
        userProFileModle: this,
        cacheTime: createTime ?? DateTime.now().millisecondsSinceEpoch);
  }

  String toJson() {
    return jsonEncode({
      'id': id,
      'siteId': siteId,
      'userId': userId,
      'registerType': registerType,
      'isEmail': isEmail,
      'isLiar': isLiar,
      'isAd': isAd,
      'isPromoter': isPromoter,
      'isCredentials': isCredentials,
      'isSubion': isSubion,
      'lastTime': lastTime,
      'exp': exp,
      'level': level,
      'status': status,
      'createTime': createTime,
      'uid': uid,
      'token': token,

      'recommendCode': recommendCode, // null,
      'type': type, // null,
      'securityAnswer': securityAnswer, // null,
      'securityQuestionId': securityQuestionId, // null,

      'account': account, // "312790696@qq.com",
      'authEmail': authEmail, // "312790696@qq.com",
      'authPhone': authPhone, // "",
      'password': password, // "ac81b21ce62e1edac4b858ebd89daf76da780533",
      'avatar': avatar, // "/avatar/af4e0c06191ea4fc6653a85ca4e4b5a5.png",
      'countryCode': countryCode, // "",
      'payPassword': payPassword, // "97a4c2b3c5988f61adc9dd0f2f78cbc0",
      'createCountry': createCountry, // "China",
      'createIsocode': createIsocode, // "CN",
      'createOs': createOs, // "Windows 10",
      'createBrowser': createBrowser, // "Chrome(94.0.4606.61)",
      'createDomain': createDomain, // "www.wigtoday.com",
      'score': score, // "50.00",
      'consume': consume, // "0.00",
      'changeScore': changeScore, // "0.00",
      'appUuid': appUuid, // "",
      'siteName': siteName, // "WIGTODAY",
      'firstName': firstName, // "zhu",
      'lastName': lastName, // "xueyi",
      'updateTime': updateTime, // 1634085077,
      'gender': gender, // 1,
      'phone': phone, // "15215628962",
      'yahoo': yahoo, // "",
      'icq': icq, // "",
      'qq': qq, // "",
      'skype': skype, // "",
      'otherInstant': otherInstant, // "",
      'country': country, // "奥地利",
      'address': address, // "TongChina Sdfasfadafdsaf",
      'email': email, // "",
      'msn': msn, // "",
      'birthday': birthday, // "03-20",
      'remark': remark
    });
  }

  void notify() {
    notifyListeners();
  }
}
