name: wigtoday_app
description: Baizhou company e-business app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter_swiper_null_safety: ^1.0.2
  webview_flutter: ^2.0.4
  flutter_datetime_picker: ^1.5.1
  flutter_pickers: ^2.1.9
  flutter_html: ^2.0.0
  image_picker: ^0.8.4+11
  image_cropper: ^1.5.0
  dio: ^4.0.6
  fluttertoast: ^8.0.9
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.13
  event_bus: ^2.0.0
  provider: ^6.0.2
  flutter_easyloading: ^3.0.3
  flutter_spinkit: ^5.0.0
  google_sign_in: ^5.3.0
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/icons/
    - assets/icons/2.0x/
    - assets/icons/3.0x/

  # fonts:
  #   - family: iconfont
  #     fonts:
  #       - asset: assets/fonts/iconfont.ttf
